<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <UserSecretsId>MetroPulse.Api.Development</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../MetroPulse.Application/MetroPulse.Application.csproj" />
    <ProjectReference Include="../MetroPulse.Infrastructure/MetroPulse.Infrastructure.csproj" />
  </ItemGroup>
</Project>
